# Generated by Django 5.2.7 on 2025-10-06 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('county', models.CharField(max_length=100)),
                ('institution_status', models.CharField(choices=[('active', 'active'), ('deleted', 'deleted'), ('suspended', 'SUSPENDED')], default='active', max_length=15)),
            ],
        ),
    ]
